spring:
  datasource:
    url: jdbc:mysql://18.158.211.226:3306/pet_v1
    username: aleksandra.mihaylova
    password: aleksandra.mihaylova123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
        host: smtp-relay.brevo.com
        username: pawfinder.team@gmail.com
        password: ASK ALEX FOR API
        port: 587
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
#  security:
#    user:
#      name: test
#      password: test1

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
       expiration: 604800000 # 7 days
